### PR TITLE
Fix for using ->fromTable() & ->withColumns()

### PR DESCRIPTION
**Pull request by ConnorHowell**
Merges the tableColumn property from the generated table column into the manually specified column.

### CODE REVIEW

**Comment by pxlrbt** [comment]
Thanks @ConnorHowell. Glad it wasn't too much trouble.

**Comment by Umar-Farooq-Shafi** [comment]
I don't know why but this update creates an issue. `Undefine array key`

**Comment by austincarpenter** [comment]
I also have the same issue. Now if one tries to append new columns to the export using `->withColumns()` and is using `->fromTable()` of course, their names don't appear as keys in the table's columns list.

**Comment by pxlrbt** [comment]
Thanks for bumping this. Missed this on the weekend. I'll write a fix.

**Comment by pxlrbt** [comment]
This should be fixed by #113

**Pull request merged**
